# Basic settings
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on

unbind C-b
set -g prefix M-Space
bind-key C-Space send-prefix

# Split windows and open it on the dame path
unbind %
unbind '"'
bind | split-window -h -c "{pane_current_path}"
bind - split-window -v -c "{pane_current_path}"
bind v split-window -h -c "{pane_current_path}"
bind s split-window -v -c "{pane_current_path}"

# Vim-style pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload config
unbind r
bind r source-file $HOME/.config/tmux/tmux.conf

# Alt+hjkl to swith panes without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Start numbering at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Alt+numner to select window
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
source-file -q "$XDG_CONFIG_HOME/tmux/themes/noctalia.conf"
