[accessibility]
ui_scale = 1.1000000089406967

[theme]
community_palette = "Gruvbox Material"
mode = "dark"
source = "community"
wallpaper_scheme = "m3-content"

[theme.templates]
enable_builtin_templates = true
enable_community_templates = true
builtin_ids = [
  "btop",
  "gtk3",
  "gtk4",
  "hyprland",
  "kcolorscheme",
  "kitty",
  "qt",
]
community_ids = [
  "telegram",
  "neovim",
  "fastfetch",
  "zathura",
  "bat",
  "tmux",
  "yazi",
]
